/glg4debug/glg4param omit_muon_processes  1.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/rat/db/set DETECTOR geo_file "error_analysis/error_analysis.geo"

/run/initialize

# BEGIN EVENT LOOP
/rat/proc count
/rat/procset update 1000

/rat/proclast outroot
#END EVENT LOOP

/tracking/storeTrajectory 1

/generator/add combo gun2:point
/generator/vtx/set opticalphoton  0  1  0 1 0.00000306 0.00000306
/generator/pos/set 0 -127 0

/run/beamOn 50000
