/glg4debug/glg4param omit_muon_processes  1.0
/glg4debug/glg4param omit_hadronic_processes  1.0
/rat/db/set DETECTOR geo_file "error_analysis/error_analysis.geo"
/run/initialize
/rat/proc count
/rat/procset update 1000
/rat/proclast outroot
/tracking/storeTrajectory 1
/generator/add combo gun2:point
/generator/vtx/set opticalphoton  0  1  0 0.25 3.06141547259e-06 3.06141547259e-06
/generator/pos/set 1.0 -127.0 0
/run/beamOn 50000
